include ("Paths.lua")

group ("Bolt/Vendor")
include (BoltDir .. BoltCoreDir .. "vendor/GLFW")
include (BoltDir .. BoltCoreDir .. "vendor/Glad")
include (BoltDir .. BoltCoreDir .. "vendor/ImGui")
include (BoltDir .. BoltLibDir .. "vendor/spdlog")
include (BoltDir .. BoltCoreDir .. "vendor/FreeType")
include (BoltDir .. BoltCoreDir .. "vendor/FreeType-GL")
include (BoltDir .. BoltCoreDir .. "vendor/Lua")
include (BoltDir .. BoltCoreDir .. "vendor/Dukglue")
group ("Bolt")
include (BoltDir .. BoltLibDir)
group("Assets")
include (BoltDir .. AssetsLibDir)
include (BoltDir .. AssetsDir)
group ("Bolt")
include (BoltDir .. BoltCoreDir)