include ("Paths.lua")

group("Resources")
include (BoltDir .. ResourcesDir .. "Converter")
group ("Bolt/Vendor")
include (BoltDir .. BoltCoreDir .. "vendor/GLFW")
include (BoltDir .. BoltCoreDir .. "vendor/Glad")
include (BoltDir .. BoltCoreDir .. "vendor/ImGui")
include (BoltDir .. BoltCoreDir .. "vendor/spdlog")
include (BoltDir .. BoltCoreDir .. "vendor/FreeType")
include (BoltDir .. BoltCoreDir .. "vendor/FreeType-GL")
include (BoltDir .. BoltCoreDir .. "vendor/Lua")
group ("Bolt")
include (BoltDir .. BoltCoreDir)