FILE_TYPE_UNKNOWN = -1
FILE_TYPE_IMAGE = 0
FILE_TYPE_MODEL = 1
FILE_TYPE_SHADER = 2
FILE_TYPE_DATA = 3

DEFAULT_OUTPUT_EXTENSION = ".bres"
DEFAULT_SETTINGS_FILE_EXTENSION = ".bcfg"
DEFAULT_OUTPUT_PACK_EXTENSION = ".pack"

FILE_EXTENSION_TYPE_MAP = {
    ".png" : FILE_TYPE_IMAGE,
    ".jpg" : FILE_TYPE_IMAGE,
    ".jpeg" : FILE_TYPE_IMAGE,
    ".tga" : FILE_TYPE_IMAGE,
    ".glsl" : FILE_TYPE_SHADER,
    ".shader" : FILE_TYPE_SHADER,
    ".obj" : FILE_TYPE_MODEL
}