name: Build

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install X11
        run: sudo apt-get install -y libx11-dev libgl1-mesa-dev xorg-dev
      - name: Checkout Bolt
        uses: actions/checkout@v2
      - name: Generate makefiles
        run: ./Linux-GenProjects.sh
        working-directory: Scripts
      - name: Make Bolt-Core
        run: make -j8 Bolt-Core

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Bolt
        uses: actions/checkout@v2
      - name: Generate projects
        run: ./Win-GenProjects.bat
        working-directory: Scripts
        shell: cmd
      - name: Build Bolt
        run: '"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin\\MSBuild.exe" Bolt.sln -m'
        shell: cmd
