name: Build

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: sudo apt-get update -y
      - name: Install make
        run: sudo apt-get install -y make
      - name: Install X11
        run: sudo apt-get install -y libx11-dev libgl1-mesa-dev xorg-dev
      - name: Checkout Bolt
        uses: actions/checkout@v2
      - name: Generate makefiles
        run: ./Linux-GenProjects.sh
        working-directory: Scripts
      - name: Make Bolt-Core
        run: make -j2 Bolt-Core

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Bolt
        run: actions/checkout@v2
      -name: Generate projects
        run: ./Win-GenProjects.bat
        working-directory: Scripts
      -name: Build Bolt
        run: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin\\MSBuild.exe" Bolt.sln -m
