name: Build-Linux
on: push
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: sudo apt-get update
      - name: Install X11
        run: sudo apt-get install -y libx11-dev libgl1-mesa-dev xorg-dev
      - name: Checkout Bolt
        uses: actions/checkout@v2
      - name: Generate makefiles
        run: ./Linux-GenProjects.sh
        working-directory: Scripts
      - name: Make Bolt-Core
        run: make -j4 Bolt-Core
      - name: Make Bolt-Editor
        run: make -j4 Bolt-Editor
